### ISSUE TITLE
Request: use default Toast style and position compared to anchored View

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [marcoscgdev/MaterialToast#2]
The current style doesn't seem to match the one of Android which is on `transient_notification.xml` file (found from [here](https://stackoverflow.com/a/8263157/878126)) :

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="?android:attr/toastFrameBackground">

    <TextView
        android:id="@android:id/message"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:layout_marginHorizontal="24dp"
        android:layout_marginVertical="15dp"
        android:layout_gravity="center_horizontal"
        android:textAppearance="@style/TextAppearance.Toast"
        android:textColor="@color/primary_text_default_material_light"
        />

</LinearLayout>
```

In addition, I've noticed that when setting the Toast to be anchored to another View, it could overlap it, as opposed to what you see when you long press a toolbar action-item.

Please use more standard look&feel by default.

**Comment by marcoscgdev** [comment]
This library was made with the purpose of using Toast with a different style from the original. Probably, creating a new library to replicate what you are asking is the most convenient.

**Comment by AndroidDeveloperLB** [comment]
@marcoscgdev But creating a different style is already possible, both on the original API of Toast class and here.
Isn't there any way that I can do it?

**Comment by AndroidDeveloperLB** [comment]
@marcoscgdev What about position? It's not nice that it can overlap the view you anchor to...
It's not styling of how it looks, per se, in this case...

**Comment by marcoscgdev** [comment]
> @marcoscgdev But creating a different style is already possible, both on the original API of Toast class and here.
> Isn't there any way that I can do it?

I have added custom view support, so you can now create new Toast styles by your own.

---

> @marcoscgdev What about position? It's not nice that it can overlap the view you anchor to...
> It's not styling of how it looks, per se, in this case...

Done. Check https://github.com/marcoscgdev/MaterialToast/issues/1.

---

```groovy
 implementation 'com.github.marcoscgdev:MaterialToast:9e0879bdd7'
```
