### ISSUE TITLE
Request: allow to use setView on the Toast that we prepare

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [marcoscgdev/MaterialToast#3]
Currently we have to have only the properties of a TextView alone. 

Please allow like that standard Toast API, to set the View of the Toast.

**Comment by marcoscgdev** [comment]
I will take a look at this.

**Comment by AndroidDeveloperLB** [comment]
@marcoscgdev I hope you understand what I mean : `setView(viewOfTheToast)`

**Comment by AndroidDeveloperLB** [comment]
Why close? It was added?

**Comment by marcoscgdev** [comment]
> Why close? It was added?

Of course, a new method `setCustomView(yourView)` has been added 😄 

I will release a new version in a few days, now you can use this version:

```groovy
 implementation 'com.github.marcoscgdev:MaterialToast:9e0879bdd7'
```
