### ISSUE TITLE
Bug: as opposed to other properties, the background is set on the companion object, making it being shared to other toasts

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [marcoscgdev/MaterialToast#4]
It should be as the others. It shouldn't affect each other.

![image](https://user-images.githubusercontent.com/5357526/101420344-9b18b800-38fa-11eb-850f-79b45fee2601.png)

**Comment by marcoscgdev** [comment]
It seems to be an error when migrating to Kotlin automatically. I will check it out.

**Comment by AndroidDeveloperLB** [comment]
@marcoscgdev Migrating? You converted from Java? Cool!
But I never saw this kind of issue when converting. Most of the issues are from nullable stuff.

**Comment by marcoscgdev** [comment]
> @marcoscgdev Migrating? You converted from Java? Cool!
> But I never saw this kind of issue when converting. Most of the issues are from nullable stuff.

Yes, Android Studio Kotlin migration plugin has also some troubles with static/companion variables. The variable "bgColor" should not be static, but the migration tool has converted it to static.

**Comment by AndroidDeveloperLB** [comment]
@marcoscgdev Really? Have you reported about this? If not, I can do it. Can you please share the original code in Java, so that I will report about this issue?

**Comment by AndroidDeveloperLB** [comment]
@marcoscgdev Also why close? Was fixed?

**Comment by marcoscgdev** [comment]
> @marcoscgdev Also why close? Was fixed?

Of course, the issue has been fixed 😄 

I will release a new version in a few days, now you can use this version:

```groovy
 implementation 'com.github.marcoscgdev:MaterialToast:9e0879bdd7'
```
